import AppKit
import Carbon.HIToolbox

/// Pastes text into whatever field has focus, then puts the user's clipboard back exactly as it was.
@MainActor
enum Paster {
    /// How long to give the target app to read the pasteboard before we restore it.
    /// Electron apps (Slack) read it asynchronously, so this can't be too tight.
    static var restoreDelay: Duration = .milliseconds(500)

    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static func paste(_ text: String) async {
        let pasteboard = NSPasteboard.general
        let saved = snapshot(pasteboard)

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        // Tells clipboard managers (Raycast, Maccy, Paste…) not to record our temporary text.
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
        pasteboard.writeObjects([item])
        let ourChangeCount = pasteboard.changeCount

        sendCommandV()

        try? await Task.sleep(for: restoreDelay)

        // If something else wrote to the clipboard meanwhile (the user copied), leave theirs alone.
        guard pasteboard.changeCount == ourChangeCount else {
            Log.info("Clipboard changed during paste, not restoring")
            return
        }
        restore(saved, to: pasteboard)
    }

    /// Every item, every type, as raw data, so images, files, rich text etc. all come back intact.
    private static func snapshot(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        (pasteboard.pasteboardItems ?? []).map { item in
            var types: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) { types[type] = data }
            }
            return types
        }
    }

    private static func restore(_ saved: [[NSPasteboard.PasteboardType: Data]], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !saved.isEmpty else { return }
        let items = saved.map { types in
            let item = NSPasteboardItem()
            for (type, data) in types { item.setData(data, forType: type) }
            return item
        }
        pasteboard.writeObjects(items)
    }

    private static func sendCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let keyCode = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }
}
